- name: Add Kubernetes apt repository key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add Kubernetes apt repository
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-lunar main # or kubernetes-bionic, kubernetes-focal, etc., depending on your Ubuntu version
    state: present
    update_cache: yes # Important: Update the APT cache after adding the repo

- name: Install kubeadm, kubelet, kubectl
  apt:
    name: "{{ item }}={{ k8s_version }}"
    state: present
    update_cache: yes
  with_items:
    - kubeadm
    - kubelet
    - kubectl
  notify: restart kubelet

- name: Initialize Kubernetes cluster (master node)
  command: kubeadm init --pod-network-cidr={{ k8s_pod_cidr }} --apiserver-cert-extra-sans={{ k8s_control_plane_ip }}
  when: "'k8s-masters' in group_names"
  register: kubeadm_init

- name: Copy kubeconfig (master node)
  run_once: true
  command:
   cmd: cp /etc/kubernetes/admin.conf ~/.kube/config
  when: "'k8s-masters' in group_names"

- name: Install CNI (Calico)
  when: "'k8s-masters' in group_names"
  command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml

- name: Join worker nodes
  command: "kubeadm join {{ k8s_control_plane_ip }}:6443 --token {{ kubeadm_init.stdout | regex_search('token\\s+(.+?)\\s+', '\\1')}} --discovery-token-ca-cert-hash sha256:{{ kubeadm_init.stdout | regex_search('sha256:(.+?)$', '\\1')}}"
  when: "'k8s-workers' in group_names"
