all:
  children:
    k8s-masters:
      hosts:
        k8smaster1:
          ansible_host: 192.168.10.129
        k8smaster2:
          ansible_host: 192.168.10.130
        k8smaster3:
          ansible_host: 192.168.10.136

    k8s-workers:
      hosts:
        k8sworker1:
          ansible_host: 192.168.10.132
        k8sworker2:
          ansible_host: 192.168.10.133

    monitoring:
      hosts:
          mon:
            ansible_host: 192.168.10.134

    logging:
      hosts:
        log:
          ansible_host: 192.168.10.135
