all:
  children:
    k8s-masters:
      hosts:
        k8s-master-1:
          ansible_host: 192.168.10.129
        k8s-master-2:
          ansible_host: 192.168.10.130
        k8s-master-3:
          ansible_host: 192.168.10.131

    k8s-workers:
      hosts:
        k8s-worker-1:
          ansible_host: 192.168.10.132
        k8s-worker-2:
          ansible_host: 192.168.10.133

    monitoring:
      hosts:
          monitoring-host:
            ansible_host: 192.168.10.134

    logging:
      hosts:
        logging-host:
          ansible_host: 192.168.10.135
