---
- hosts: all
  become: true
  roles:
    - common
    - network
    - containerd
    - cert

- hosts: k8s-masters
  become: true
  roles:
    - kubernetes_setup

- hosts: k8s-workers
  become: true
  roles:
    - kubernetes_setup

- hosts: monitoring
  become: true
  roles:
    - prometheus
    - grafana

- hosts: logging
  become: true
  roles:
    - elk
    - kibana
